# This file was generated by GoReleaser. DO NOT EDIT.
cask "oolong" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "3aacddf49e300b0fd9cc7ca267e03b0d147b642c029f4c6330dc48c930ba0a7f"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0c1ada98e2d6843542950d8844624041107ef3715b0449ea3afe8ae89f2791bf"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fcd81482c38e13057d7e2f55630b3a5f4d88d26af460664ba4c3135c5e90a2a2"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ae777d936a4084b62cdf92714ed8a8f9dfaf04642184fc257ebb0546a5717b6"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oolong"
  desc "Simple ephemeral chat with OpenAI models in your terminal"
  homepage "https://github.com/dicedatalore/oolong"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oolong"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oolong"]
    end
  end

  # No zap stanza required

end
