# This file was generated by GoReleaser. DO NOT EDIT.
cask "oolong" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "e93b5509de0adc5c91ae749c987d08e877085e66b0cf0bc379aea981375aaade"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fee35fd8079f97c4f2af1b1bf533327c7d99b6f8ce58c4fbc0e4e60bf1b1a270"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "66b9c589b296fa16265cd102df0364b6966b023dbea6fbd1dac73849a21e16cc"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5ec93bd2a9dc048b715ac71ac9a004658814feef6693a73340378f3f6de02389"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oolong"
  desc "Simple ephemeral chat with OpenAI models in your terminal"
  homepage "https://github.com/dicedatalore/oolong"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oolong"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oolong"]
    end
  end

  # No zap stanza required

end
