# This file was generated by GoReleaser. DO NOT EDIT.
cask "oolong" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6cad586ca167d81d546db4cc2084f7f906c4e91423b49cc22e4f0d2e10fea95b"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "beec2f3105ad069b030c047135c8812999c4558945df269aed4ade5d5bfa15aa"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c915f50ac26b3646376e169d36df022f66488c02c63eba150ce64c5ea2821a3a"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a605ab4cddf6e6d95da01e5e2d89824f2f747d7ee13b00bd5911da72107ef732"
      url "https://github.com/dicedatalore/oolong/releases/download/v#{version}/oolong_#{version}_linux_arm64.tar.gz"
    end
  end

  name "oolong"
  desc "Simple ephemeral chat with OpenAI models in your terminal"
  homepage "https://github.com/dicedatalore/oolong"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oolong"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oolong"]
    end
  end

  # No zap stanza required

end
