# This file was generated by GoReleaser. DO NOT EDIT.
cask "sencha" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "8061626ba2f178fbc7169867f5eeebc7b2187a09e20240c2baa5ba051a242e44"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "e715da2b1e3d63320d9989c67c4818f88dd79f8edc3aadb3e0cee6fd411d441f"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "567b27b0d385d304a7be1af96e768a7a9ba9d0fd393b4f3f797b67657d4da907"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "71973731eedc53b6ef8321144e19baaaab54e598f1a7bb13d03829b5dea4c426"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sencha"
  desc "Run coding agents in Docker Sandboxes on a remote server over SSH"
  homepage "https://github.com/dicedatalore/sencha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sencha"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sencha"]
    end
  end

  # No zap stanza required

end
