# This file was generated by GoReleaser. DO NOT EDIT.
cask "sencha" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "99589c2818c07d19f0b34d665c408ce3dfe2b8512c4acd7bc0b294b611a2156c"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "068e61cf67f1a2a15c508f618ed5e3eceb6ed0aea7e0c03628817871beb131dd"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6754585a85a5c754c87af959b209e057a1fd9154bd7a477e7dff78f9fe33420"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "ef1053318f57ef8e1d3c94208f927d34539bf970ff8e7d97c77f83031f46fa76"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sencha"
  desc "Run coding agents in Docker Sandboxes on a remote server over SSH"
  homepage "https://github.com/dicedatalore/sencha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sencha"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sencha"]
    end
  end

  # No zap stanza required

end
