# This file was generated by GoReleaser. DO NOT EDIT.
cask "sencha" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1f649cddc44c657db8f946ece66cc014b4a7ccedf875aa5be92f51ee5dfc6e41"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "13e7d0f1ac9d0d001f97b99a183397b6bc02a9032c449ff3989d4375d1e57380"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6de3b2d33938176838237461f8b30ab9085509f762e9b3bf06b3dba1ab011303"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "71172b9f84eae04a3abe2dfcdae91e096e03f9b8773e03cc9601542ec743f11c"
      url "https://github.com/dicedatalore/sencha/releases/download/v#{version}/sencha-#{version}-linux-arm64.tar.gz"
    end
  end

  name "sencha"
  desc "Run coding agents in Docker Sandboxes on a remote server over SSH"
  homepage "https://github.com/dicedatalore/sencha"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sencha"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sencha"]
    end
  end

  # No zap stanza required

end
